## 1- Secret
## 2- ConfigMap
## 3- Mongo Deployment
## 4- Mongo Express Deployment
## 
## kubectl apply -f mongo-secret.yaml
## kubectl apply -f mongo-configmap.yaml
## kubectl apply -f mongo-deployment.yaml
## kubectl apply -f mongo-express-deployment.yaml